chef-server-webui/config/routes.rb
#
# Author:: Adam Jacob (<adam@opscode.com>)
# Author:: Daniel DeLeo (<dan@opscode.com>)
# Copyright:: Copyright (c) 2008-2010 Opscode, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ChefServerWebui::Application.routes.draw do
  resources :nodes, :id => /[^\/]+/
  match "/nodes/_environments/:environment_id", :to => "nodes#index", :as => :nodes_by_environment

  resources :clients, :id => /[^\/]+/
  resources :roles

  resources :environments do
    match "/recipes", :only => :get, :to => "environments#list_recipes"
    match "/cookbooks", :to => "environments#list_cookbooks", :as => :cookbooks, :only => :get
    match "/nodes", :to => "environments#list_nodes", :as => :nodes, :only => :get
    match "/select", :to => "environments#select_environment", :as => :select, :only => :get
  end

  # match '/environments/create' :to => "environments#create", :as => :environments_create

  match "/status", :to => "status#index", :as => :status, :only => :get

  resources :searches, :path => "search", :controller => "search"
  match "/search/:search_id/entries", :only => 'get', :to => "search_entries", :action => "index"
  match "/search/:search_id/entries", :only => 'post', :to => "search_entries", :action => "create"
  match "/search/:search_id/entries/:id", :only => 'get', :to => "search_entries", :action => "show"
  match "/search/:search_id/entries/:id", :only => 'put', :to => "search_entries", :action => "create"
  match "/search/:search_id/entries/:id", :only => 'post', :to => "search_entries", :action => "update"
  match "/search/:search_id/entries/:id", :only => 'delete', :to => "search_entries", :action => "destroy"

  match "/cookbooks/_attribute_files", :to => "cookbooks#attribute_files"
  match "/cookbooks/_recipe_files", :to => "cookbooks#recipe_files"
  match "/cookbooks/_definition_files", :to => "cookbooks#definition_files"
  match "/cookbooks/_library_files", :to => "cookbooks#library_files"
  match "/cookbooks/_environments/:environment_id", :to => "cookbooks#index", :as => :cookbooks_by_environment

  match "/cookbooks/:cookbook_id", :cookbook_id => /[\w\.]+/, :only => :get, :to => "cookbooks#cb_versions"
  match "/cookbooks/:cookbook_id/:cb_version", :cb_version => /[\w\.]+/, :only => :get, :to => "cookbooks#show", :as => :show_specific_version_cookbook
  resources :cookbooks

  resources :clients

  match "/databags/:databag_id/databag_items", :only => :get, :to => "databags#show", :id=>":databag_id"

  resources :databags do
    resources :databag_items
  end

  match '/openid/consumer', :to => 'openid_consumer#index', :as => :openid_consumer
  match '/openid/consumer/start', :to => 'openid_consumer#start', :as => :openid_consumer_start
  match '/openid/consumer/login', :to => 'openid_consumer#login', :as => :openid_consumer_login
  match '/openid/consumer/complete', :to => 'openid_consumer#complete', :as => :openid_consumer_complete
  match '/openid/consumer/logout', :to => 'openid_consumer#logout', :as => :openid_consumer_logout

  match '/login', :to => 'users#login', :as => :users_login
  match '/logout', :to => 'users#logout', :as => :users_logout

  match '/users', :to => 'users#index', :as => :users
  match '/users/create', :to => 'users#create', :as => :users_create
  match '/users/start', :to => 'users#start', :as => :users_start

  match '/users/login', :to => 'users#login', :as => :users_login
  match '/users/login_exec', :to => 'users#login_exec', :as => :users_login_exec
  match '/users/complete', :to => 'users#complete', :as => :users_complete
  match '/users/logout', :to => 'users#logout', :as => :users_logout
  match '/users/new', :to => 'users#new', :as => :users_new
  match '/users/:user_id/edit', :to => 'users#edit', :as => :users_edit
  match '/users/:user_id', :to => 'users#show', :as => :users_show
  match '/users/:user_id/delete', :only => :delete, :to => 'users#destroy', :as => :users_delete
  match '/users/:user_id/update', :only => :put, :to => 'users#update', :as => :users_update

  match '/', :to => 'nodes#index', :as => :top
end

chef-server-webui/app/controllers/databags_controller.rb
#
# Author:: Nuo Yan (<nuo@opscode.com>)
# Copyright:: Copyright (c) 2008 Opscode, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'chef/data_bag'

class DatabagsController < ApplicationController

  respond_to :html, :json
  before_filter :login_required
  before_filter :require_admin

  def new
    @databag = Chef::DataBag.new
  end

  def create
    begin
      @databag = Chef::DataBag.new
      @databag.name params[:name]
      @databag.create
      redirect_to databags_url, :notice => "Created Databag #{@databag.name}"
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      flash[:error] = "Could not create databag"
      render :new
    end
  end

  def index
    @databags = begin
                  Chef::REST.new(Chef::Config[:chef_server_url]).get_rest("data")
                rescue => e
                  Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
                  flash[:error] = "Could not list databags"
                  {}
                end
  end

  def show
    begin
      @databag_name = params[:id]
      r = Chef::REST.new(Chef::Config[:chef_server_url])
      @databag = r.get_rest("data/#{params[:id]}")
      raise NotFound unless @databag
      display @databag
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      @databags = Chef::DataBag.list
      flash[:error] = "Could not load databag"
      render :index
    end
  end

  def destroy
    begin
      r = Chef::REST.new(Chef::Config[:chef_server_url])
      r.delete_rest("data/#{params[:id]}")
      redirect_to databags_url, :notice => "Data bag #{params[:id]} deleted successfully"
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      @databags = Chef::DataBag.list
      flash[:error] = "Could not delete databag"
      render :index
    end
  end

end

chef-server-webui/app/views/databags/_form.html.haml
.content
  .inner
    %div.group.form
      %label.label Name
      = text_field_tag "name", params.has_key?(:id) ? h(params[:id]) : @databag.name, :id => "databag_name", :class => "text_field"
      %span.description The name of the Databag

    = form_tag form_url, :method => :post, :id => form_id, :class => 'form' do
      %div.group
        .actions-bar
          .actions= submit_tag submit_name, :id => submit_id, :class => 'button'

chef-server-webui/app/views/databags/_item_navigation.html.haml
.secondary-navigation
  %ul
    %li{ :class => "first #{active == 'index' ? "active" : ''}"}= link_to('List', databags_path)
    %li{ :class => (active == 'create_item' ? "active" : '')}= link_to('Create Item', new_databag_databag_item_path(@databag_name))
    - if active != 'create' && active != 'index'
      %li{ :class => (active == 'show' ? "active" : '')}= link_to('Show', databag_path(params[:id]))
      %li= link_to('Delete', databag_path(params[:id]), :method => "delete", :confirm => "Really delete Databag #{params[:id]}? There is no undo.")
  .clear

chef-server-webui/app/views/databags/_navigation.html.haml
.secondary-navigation
  %ul
    %li{ :class => "first #{active == 'index' ? "active" : ''}"}= link_to('List', databags_path)
    %li{ :class => (active == 'create' ? "active" : '')}= link_to('Create', new_databag_path)
    - if active != 'create' && active != 'index'
      %li{ :class => (active == 'show' ? "active" : '')}= link_to('Show', databag_path(@databag_name))
      %li{ :class => (active == 'edit' ? "active" : '')}= link_to('Edit', edit_databag_path(@databag_name))
      %li= link_to('Delete', databag_path(@databag_name), :method => "delete", :confirm => "Really delete Databag #{@databag_name}? There is no undo.")
  .clear

chef-server-webui/app/views/databags/edit.html.haml
.block#block-tables
  .content
    %h2.title= "Databag: #{params[:id]}"
    .inner
      = render('navigation', :active => 'edit')
  = render('form', :header => "Edit Databag", :form_id => 'edit_databag', :submit_name => "Edit Databag", :submit_id => "edit_databag_button", :form_for => 'edit', :form_url => databag_path(params[:id]))

chef-server-webui/app/views/databags/index.html.haml
.block#block-tables
  .content
    %h2.title Databags
    .inner
      = render('navigation', :active => 'index')
    .content
      .inner
        %table.table
          %thead
            %tr
              %th.first{:colspan => 2} Databag Name
              %th &nbsp;
              %th.last &nbsp;
          %tbody
            - @databags.sort_by {|key, value| value.downcase}.each_with_index do |databag, index|
              %tr{:class => "#{index % 2 == 1 ? 'odd' : 'even'}"}
                %td{:colspan => 2}= link_to databag[0], databag_path(databag[0])
                %td
                  = link_to('Edit', databag_path(databag[0]))
                  |
                  = link_to('Delete', databag_path(databag[0]), :method => "delete", :confirm => "Really delete Databag #{databag[0]}?  There is no undo.")

chef-server-webui/app/views/databags/new.html.haml
.block#block-tables
  .content
    %h2.title= "Databag"
    .inner
      = render('navigation', :active => 'create')
  = render('form', :header => "Create new Databag", :form_id => 'create_databag', :submit_name => "Create Databag", :submit_id => "create_databag_button", :form_for => 'create', :form_url => databags_path)

chef-server-webui/app/views/databags/show.html.haml
.block#block-text
  .content
    %h2.title= "Databag: #{@databag_name}"
    .inner
      = render('item_navigation', :active => 'show')
    .content
      .inner
        %table.table
          %tr
            %th.first{:colspan => 2} Databag Items
            %th &nbsp;
            %th.last &nbsp;
            - @databag.sort.each_with_index do |databag_item_uri, index|
              %tr{:class => "#{index % 2 == 1 ? 'odd' : 'even'}"}
                %td{:colspan => 2}= link_to databag_item_uri[0], databag_databag_item_path(@databag_name, databag_item_uri[0])
                %td
                  = link_to('Edit', edit_databag_databag_item_path(@databag_name, databag_item_uri[0]))
                  |
                  = link_to('Delete', databag_databag_item_path(@databag_name, databag_item_uri[0]), :method => "delete", :confirm => "Really delete Databag Item #{databag_item_uri[0]}?  There is no undo.")