chef-server-webui/config/routes.rb
#
# Author:: Adam Jacob (<adam@opscode.com>)
# Author:: Daniel DeLeo (<dan@opscode.com>)
# Copyright:: Copyright (c) 2008-2010 Opscode, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ChefServerWebui::Application.routes.draw do
  resources :nodes, :id => /[^\/]+/
  match "/nodes/_environments/:environment_id", :to => "nodes#index", :as => :nodes_by_environment

  resources :clients, :id => /[^\/]+/
  resources :roles

  resources :environments do
    match "/recipes", :only => :get, :to => "environments#list_recipes"
    match "/cookbooks", :to => "environments#list_cookbooks", :as => :cookbooks, :only => :get
    match "/nodes", :to => "environments#list_nodes", :as => :nodes, :only => :get
    match "/select", :to => "environments#select_environment", :as => :select, :only => :get
  end

  # match '/environments/create' :to => "environments#create", :as => :environments_create

  match "/status", :to => "status#index", :as => :status, :only => :get

  resources :searches, :path => "search", :controller => "search"
  match "/search/:search_id/entries", :only => 'get', :to => "search_entries", :action => "index"
  match "/search/:search_id/entries", :only => 'post', :to => "search_entries", :action => "create"
  match "/search/:search_id/entries/:id", :only => 'get', :to => "search_entries", :action => "show"
  match "/search/:search_id/entries/:id", :only => 'put', :to => "search_entries", :action => "create"
  match "/search/:search_id/entries/:id", :only => 'post', :to => "search_entries", :action => "update"
  match "/search/:search_id/entries/:id", :only => 'delete', :to => "search_entries", :action => "destroy"

  match "/cookbooks/_attribute_files", :to => "cookbooks#attribute_files"
  match "/cookbooks/_recipe_files", :to => "cookbooks#recipe_files"
  match "/cookbooks/_definition_files", :to => "cookbooks#definition_files"
  match "/cookbooks/_library_files", :to => "cookbooks#library_files"
  match "/cookbooks/_environments/:environment_id", :to => "cookbooks#index", :as => :cookbooks_by_environment

  match "/cookbooks/:cookbook_id", :cookbook_id => /[\w\.]+/, :only => :get, :to => "cookbooks#cb_versions"
  match "/cookbooks/:cookbook_id/:cb_version", :cb_version => /[\w\.]+/, :only => :get, :to => "cookbooks#show", :as => :show_specific_version_cookbook
  resources :cookbooks

  resources :clients

  match "/databags/:databag_id/databag_items", :only => :get, :to => "databags#show", :id=>":databag_id"

  resources :databags do
    resources :databag_items
  end

  match '/openid/consumer', :to => 'openid_consumer#index', :as => :openid_consumer
  match '/openid/consumer/start', :to => 'openid_consumer#start', :as => :openid_consumer_start
  match '/openid/consumer/login', :to => 'openid_consumer#login', :as => :openid_consumer_login
  match '/openid/consumer/complete', :to => 'openid_consumer#complete', :as => :openid_consumer_complete
  match '/openid/consumer/logout', :to => 'openid_consumer#logout', :as => :openid_consumer_logout

  match '/login', :to => 'users#login', :as => :users_login
  match '/logout', :to => 'users#logout', :as => :users_logout

  match '/users', :to => 'users#index', :as => :users
  match '/users/create', :to => 'users#create', :as => :users_create
  match '/users/start', :to => 'users#start', :as => :users_start

  match '/users/login', :to => 'users#login', :as => :users_login
  match '/users/login_exec', :to => 'users#login_exec', :as => :users_login_exec
  match '/users/complete', :to => 'users#complete', :as => :users_complete
  match '/users/logout', :to => 'users#logout', :as => :users_logout
  match '/users/new', :to => 'users#new', :as => :users_new
  match '/users/:user_id/edit', :to => 'users#edit', :as => :users_edit
  match '/users/:user_id', :to => 'users#show', :as => :users_show
  match '/users/:user_id/delete', :only => :delete, :to => 'users#destroy', :as => :users_delete
  match '/users/:user_id/update', :only => :put, :to => 'users#update', :as => :users_update

  match '/', :to => 'nodes#index', :as => :top
end

chef-server-webui/app/views/layouts/_jsonedit.html.haml
%script= raw("$(document).ready(function() { $$(\"jsonstr\").value = JSON.stringify(#{json}); if (BCJTEP.build()) { $$(\"results\").innerHTML = \"&nbsp;\"; $$(\"editortab\").className = \"show\"; $$(\"searchtab\").className = \"show\"; }});")
%div#jsoneditor
  %div#treecontainer
    %div#div1
  %div#tabcontainer
    %div#tab-container-1.tablayout
      %ul#tab-container-1-nav.tablayout
        %li#searchtab.noshow
          %a{ :href => "#tab1"} search
        %li#editortab.noshow
          %a{ :href => "#tab2"} editor
        %li#sourcetab
          %a{ :href => "#tab3"} source
      %div#tab1.tab
        %table.icanhastable
          %tr
            %td
              %span search :
              %input#keyword{:type => "text"}
              %input#search{:type => "button", :value => "Find"}
          %tr
            %td
              %div#results &nbsp;
      %div#tab2.tab
        %table.icanhastable
          %tr
            %td
              %div#add.button{:title => "Add a new attribute"}
              %div#delete.button{:title => "Delete current attribute"}
              %div#savedstatus{:style => "display:none;"}
                %img{ :src=> "/assets/jsonedit/saved.png"}
                %span Saved!
              %div#deletedstatus{:style => "display:none;"}
                %img{ :src=> "/assets/jsonedit/deleted.png"}
                %span Deleted!
            %td
              type :
              %select#jsontypes
                %option Select Type
          %tr
            %td{:colspan => "2"}
              %div#jsonnameinput
                name :
                %input#jsonname{:type => "text", :size=>"55", :class => ""}
          %tr
            %td{:colspan => "2"}
              %textarea#jsonvalue{:wrap => "virtual", :cols => "55", :rows => "5", :class => ""}
          %tr
            %td{:colspan => "2"}
              %div#jsonpath &nbsp;
              %div#jsonmode &nbsp;
          %tr
            %td{:style => "text-align:left !important"}
              %input#autodetect{:type => "checkbox", :checked=> "true"}
              %label{:for => "autodetect"} Autodetect type of attribute?
            %td
              %input#savebutton{:type => "button", :value => "Save Attribute"}
              %input#addbutton{:type => "button", :value => "Add Attribute"}
      %div#tab3.tab
        %div#tab-container-2.tablayout.nested
          %ul#tab-container-2-nav.tablayout
            %li
              %a{ :href => "#tab3a" } json
          %div#tab1a.tabn
            %table.icanhastable
              %tr
                %td
                  %div#refresh.button{:title => "Reload JSON from Tree"}
                  %div#buildbutton.button{:title => "Load JSON from Source"}
              %tr
                %td
                  %textarea#jsonstr{:wrap => "virtual", :cols => "55", :rows => "10", :class => ""}
      %div#console
        %div#bar
          %a#consolebar Error Console
        %div#log

chef-server-webui/app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %meta{ "http-equiv" => "content-type", :content => "text/html; charset=utf-8" }
    %title Chef Server
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body
    #container
      #header
        %h1
          = link_to "Chef Server", top_path
          %label{:for => 'environment-select'} Environment:
          %select{:name => 'environment-select', :onchange => 'jump(this)', :size => 1, :class => 'title-select'}
            - current_env = session[:environment]
            %option{:value => environment_select_url('_none'), :selected => current_env == nil} None
            - @environments.each do |env|
              %option{:value => environment_select_path(env), :selected => current_env == env}= env
        #user-navigation
          %ul
            - if session[:user]
              %li= link_to "Edit account", users_edit_path(session[:user])
              %li= link_to "Logout #{h session[:user]} (#{session[:level].to_s})", users_logout_path, :confirm => "Are you sure you want to logout?"
            - else
              %li= link_to "Login", users_login_path, :rel => "facebox"
          .clear
        #main-navigation
          %ul
            = nav_link_item("Environments", :environments)
            = nav_link_item("Search", :searches)
            = nav_link_item("Status", :status)
            = nav_link_item("Roles", :roles)
            = nav_link_item("Nodes", :nodes)
            = nav_link_item("Cookbooks", :cookbooks)
            = nav_link_item("Databags", :databags)
            = nav_link_item("Clients", :clients)
            = nav_link_item("Users", :users)
          .clear
      #wrapper
        #main
          - unless flash.empty?
            .block#block-messages
              .content
                %h2.title Messages
                .inner
                  .flash
                    - flash.each do |type, msg|
                      %div{:class => "message #{type}"}
                        %p= msg
          = yield
          #footer
            .block
              %p= raw("Version #{chef_version} &mdash; Copyright &copy; 2009-#{Time.now.year} Opscode")
        #sidebar
          .block.notice#sidebar_block_notice= yield :sidebar_block_notice
          .block#sidebar_block= yield :sidebar_block
        .clear

chef-server-webui/app/views/layouts/login.html.haml
!!! XML
!!! 5
%html
  %head
    %meta{ "http-equiv" => "content-type", :content => "text/html; charset=utf-8" }
    %title Chef Server
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"

  %body
    #container
      #header
        %h1= link_to "Chef Server", top_path
      #wrapper
        #main.loginPage
          - unless flash.empty?
            .block#block-messages
              .content
                %h2.title Messages
                .inner
                  .flash
                    - flash.each do |type, msg|
                      %div{:class => "message #{type}"}
                        %p= msg
          = yield
          #footer
            .block
              %p= raw("Version #{chef_version} &mdash; Copyright &copy; 2009-#{Time.now.year} Opscode")
        #sidebar
          .block.notice#sidebar_block_notice= yield :sidebar_block_notice
          .block#sidebar_block= yield :sidebar_block
        .clear