chef-server-webui/config/routes.rb
#
# Author:: Adam Jacob (<adam@opscode.com>)
# Author:: Daniel DeLeo (<dan@opscode.com>)
# Copyright:: Copyright (c) 2008-2010 Opscode, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ChefServerWebui::Application.routes.draw do
  resources :nodes, :id => /[^\/]+/
  match "/nodes/_environments/:environment_id", :to => "nodes#index", :as => :nodes_by_environment

  resources :clients, :id => /[^\/]+/
  resources :roles

  resources :environments do
    match "/recipes", :only => :get, :to => "environments#list_recipes"
    match "/cookbooks", :to => "environments#list_cookbooks", :as => :cookbooks, :only => :get
    match "/nodes", :to => "environments#list_nodes", :as => :nodes, :only => :get
    match "/select", :to => "environments#select_environment", :as => :select, :only => :get
  end

  # match '/environments/create' :to => "environments#create", :as => :environments_create

  match "/status", :to => "status#index", :as => :status, :only => :get

  resources :searches, :path => "search", :controller => "search"
  match "/search/:search_id/entries", :only => 'get', :to => "search_entries", :action => "index"
  match "/search/:search_id/entries", :only => 'post', :to => "search_entries", :action => "create"
  match "/search/:search_id/entries/:id", :only => 'get', :to => "search_entries", :action => "show"
  match "/search/:search_id/entries/:id", :only => 'put', :to => "search_entries", :action => "create"
  match "/search/:search_id/entries/:id", :only => 'post', :to => "search_entries", :action => "update"
  match "/search/:search_id/entries/:id", :only => 'delete', :to => "search_entries", :action => "destroy"

  match "/cookbooks/_attribute_files", :to => "cookbooks#attribute_files"
  match "/cookbooks/_recipe_files", :to => "cookbooks#recipe_files"
  match "/cookbooks/_definition_files", :to => "cookbooks#definition_files"
  match "/cookbooks/_library_files", :to => "cookbooks#library_files"
  match "/cookbooks/_environments/:environment_id", :to => "cookbooks#index", :as => :cookbooks_by_environment

  match "/cookbooks/:cookbook_id", :cookbook_id => /[\w\.]+/, :only => :get, :to => "cookbooks#cb_versions"
  match "/cookbooks/:cookbook_id/:cb_version", :cb_version => /[\w\.]+/, :only => :get, :to => "cookbooks#show", :as => :show_specific_version_cookbook
  resources :cookbooks

  resources :clients

  match "/databags/:databag_id/databag_items", :only => :get, :to => "databags#show", :id=>":databag_id"

  resources :databags do
    resources :databag_items
  end

  match '/openid/consumer', :to => 'openid_consumer#index', :as => :openid_consumer
  match '/openid/consumer/start', :to => 'openid_consumer#start', :as => :openid_consumer_start
  match '/openid/consumer/login', :to => 'openid_consumer#login', :as => :openid_consumer_login
  match '/openid/consumer/complete', :to => 'openid_consumer#complete', :as => :openid_consumer_complete
  match '/openid/consumer/logout', :to => 'openid_consumer#logout', :as => :openid_consumer_logout

  match '/login', :to => 'users#login', :as => :users_login
  match '/logout', :to => 'users#logout', :as => :users_logout

  match '/users', :to => 'users#index', :as => :users
  match '/users/create', :to => 'users#create', :as => :users_create
  match '/users/start', :to => 'users#start', :as => :users_start

  match '/users/login', :to => 'users#login', :as => :users_login
  match '/users/login_exec', :to => 'users#login_exec', :as => :users_login_exec
  match '/users/complete', :to => 'users#complete', :as => :users_complete
  match '/users/logout', :to => 'users#logout', :as => :users_logout
  match '/users/new', :to => 'users#new', :as => :users_new
  match '/users/:user_id/edit', :to => 'users#edit', :as => :users_edit
  match '/users/:user_id', :to => 'users#show', :as => :users_show
  match '/users/:user_id/delete', :only => :delete, :to => 'users#destroy', :as => :users_delete
  match '/users/:user_id/update', :only => :put, :to => 'users#update', :as => :users_update

  match '/', :to => 'nodes#index', :as => :top
end

chef-server-webui/app/controllers/environments_controller.rb
#
# Author:: Stephen Delano (<stephen@opscode.com>)
# Copyright:: Copyright (c) 2010 Opscode, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'chef/environment'

class EnvironmentsController < ApplicationController

  respond_to :html, :json
  before_filter :login_required
  before_filter :require_admin, :only => [:create, :update, :destroy]

  # GET /environments
  def index
    @environment_list = begin
                          Chef::Environment.list
                        rescue => e
                          Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
                          flash[:error] = "Could not list environments"
                          {}
                        end
  end

  # GET /environments/:id
  def show
    load_environment
  end

  # GET /environemnts/new
  def new
    @environment = Chef::Environment.new
    load_cookbooks
    render :new
  end

  # POST /environments
  def create
    @environment = Chef::Environment.new
    if @environment.update_from_params(processed_params=process_params)
      begin
        @environment.create
        redirect_to environments_url :notice => "Created Environment #{@environment.name}"
      rescue Net::HTTPServerException => e
        if conflict?(e)
          Chef::Log.debug("Got 409 conflict creating environment #{params[:name]}\n#{format_exception(e)}")
          redirect_to new_environment_url, :error => "An environment with that name already exists"
        elsif forbidden?(e)
          # Currently it's not possible to get 403 here. I leave the code here for completeness and may be useful in the future.[nuo]
          Chef::Log.debug("Got 403 forbidden creating environment #{params[:name]}\n#{format_exception(e)}")
          redirect_to new_environment_url, :error => "Permission Denied. You do not have permission to create an environment."
        else
          Chef::Log.error("Error communicating with the API server\n#{format_exception(e)}")
          raise
        end
      end
    else
      load_cookbooks
      # By rendering :new, the view shows errors from @environment.invalid_fields
      render :new
    end
  end

  # GET /environments/:id/edit
  def edit
    load_environment
    if @environment.name == "_default"
      msg = { :warning => "The '_default' environment cannot be edited." }
      redirect_to environments_url, :flash => msg
      return
    end
    load_cookbooks
  end

  # PUT /environments/:id
  def update
    load_environment
    if @environment.update_from_params(process_params(params[:id]))
      begin
        @environment.save
        redirect_to environment_url(@environment.name), :notice => "Updated Environment #{@environment.name}"
      rescue Net::HTTPServerException => e
        if forbidden?(e)
          # Currently it's not possible to get 403 here. I leave the code here for completeness and may be useful in the future.[nuo]
          Chef::Log.debug("Got 403 forbidden updating environment #{params[:name]}\n#{format_exception(e)}")
          redirect_to edit_environment_url, :error => "Permission Denied. You do not have permission to update an environment."
        else
          Chef::Log.error("Error communicating with the API server\n#{format_exception(e)}")
          raise
        end
      end
    else
      load_cookbooks
      # By rendering :new, the view shows errors from @environment.invalid_fields
      render :edit
    end
  end

  # DELETE /environments/:id
  def destroy
    begin
      @environment = Chef::Environment.load(params[:id])
      @environment.destroy
      redirect_to environments_url, :notice => "Environment #{@environment.name} deleted successfully."
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      @environment_list = Chef::Environment.list()
      flash[:error] = "Could not delete environment #{params[:id]}: #{e.message}"
      render :index
    end
  end

  # GET /environments/:environment_id/cookbooks
  def list_cookbooks
    # TODO: rescue loading the environment
    @environment = Chef::Environment.load(params[:environment_id])
    @cookbooks = begin
                   r = Chef::REST.new(Chef::Config[:chef_server_url])
                   r.get_rest("/environments/#{params[:environment_id]}/cookbooks").inject({}) do |res, (cookbook, url)|
                     # we just want the cookbook name and the version
                     res[cookbook] = url.split('/').last
                     res
                   end
                 rescue => e
                   Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
                   flash[:error] = "Could not load cookbooks for environment #{params[:environment_id]}"
                   {}
                 end
  end

  # GET /environments/:environment_id/nodes
  def list_nodes
    # TODO: rescue loading the environment
    @environment = Chef::Environment.load(params[:environment_id])
    @nodes = begin
               r = Chef::REST.new(Chef::Config[:chef_server_url])
               r.get_rest("/environments/#{params[:environment_id]}/nodes").keys.sort
             rescue => e
               Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
               flash[:error] = "Could not load nodes for environment #{params[:environment_id]}"
               []
             end
  end

  # GET /environments/:environment/recipes
  def list_recipes
    respond_with :recipes => list_available_recipes_for(params[:environment_id])
  end

  # GET /environments/:environment_id/set
  def select_environment
    name = params[:environment_id]
    referer = request.referer || nodes_url
    if name == '_none'
      session[:environment] = nil
    else
      # TODO: check if environment exists
      session[:environment] = name
    end
    redirect_to referer
  end

  private

  def load_environment
    @environment = begin
      Chef::Environment.load(params[:id])
    rescue Net::HTTPServerException => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      flash[:error] = "Could not load environment #{params[:id]}"
      @environment = Chef::Environment.new
      false
    end
  end

  def load_cookbooks
    begin
      # @cookbooks is a hash, keys are cookbook names, values are their URIs.
      @cookbooks = Chef::REST.new(Chef::Config[:chef_server_url]).get_rest("cookbooks").keys.sort
    rescue Net::HTTPServerException => e
      Chef::Log.error(format_exception(e))
      redirect_to new_environment_url, :error => "Could not load the list of available cookbooks."
    end
  end

  def process_params(name=params[:name])
    {:name => name, :description => params[:description], :default_attributes => params[:default_attributes], :override_attributes => params[:override_attributes], :cookbook_version => search_params_for_cookbook_version_constraints}
  end

  def search_params_for_cookbook_version_constraints
    cookbook_version_constraints = {}
    index = 0
    params.each do |k,v|
      cookbook_name_box_id = k[/cookbook_name_(\d+)/, 1]
      unless cookbook_name_box_id.nil? || v.nil? || v.empty?
        cookbook_version_constraints[index] = v + " " + params["operator_#{cookbook_name_box_id}"] + " " + params["cookbook_version_#{cookbook_name_box_id}"].strip # e.g. {"0" => "foo > 0.3.0"}
        index = index + 1
      end
    end
    Chef::Log.debug("cookbook version constraints are: #{cookbook_version_constraints.inspect}")
    cookbook_version_constraints
  end
end

chef-server-webui/app/helpers/environments_helper.rb
module EnvironmentsHelper
  def cookbook_version_constraints
    @environment.cookbook_versions.inject({}) do |ans, (cb, vc)|
      op, version = vc.split(" ")
      ans[cb] = { "version" => version, "op" => op }
      ans
    end
  end

  def constraint_operators
    %w(~> >= > = < <=)
  end
end

chef-server-webui/app/views/environments/_form.html.erb
<div class="content environmentFormContainer">
  <%= form_tag form_url, :method => (method || :post), :id => form_id, :class => 'form' do %>
    <% unless form_for == 'edit' %>
      <div class="group form">
        <label class="label" for="environment_name">Name</label>
        <% if !@environment.invalid_fields[:name].nil? && @environment.invalid_fields[:name].size != 0 %>
          <span class="inline_error_message">The environment name contains illegal characters. The following characters are allowed: a-z, A-Z, 0-9, _, and -.</span>
        <% end %>

        <%= text_field_tag "name", params.has_key?(:name) ? h(params[:name]) : @environment.name, :id => "environment_name", :class => "text_field" %>
        <span class="description">The name of the Environment</span>
      </div>
    <% end %>

    <div class="group form">
      <label class="label" for="environment_description">Description</label>
      <%= text_area_tag "description", params.has_key?(:description) ? h(params[:description]) : @environment.description, :class => "text_area", :id => "environment_description" %>
      <span class="description">A description of this Environment</span>
    </div>

    <div class="group form cbVerPicker" id=<%=form_for%>>
      <label class="label" for="cookbook_version_constraints">Cookbook Version Constraints</label>
      <% if !@environment.invalid_fields[:cookbook_version].nil? && !@environment.invalid_fields[:cookbook_version].empty? %>
        <span class="inline_error_message" id='error'>There was a problem in one of your constraints. Please enter version constraints in acceptable formats (e.g. 0.0.0). </span>
      <% end %>
      <table class="table" id="cbVerPickerTable">
        <tbody>
          <tr>
            <th class = "first" id="CookbookVersionConstraints">Name</th>
            <th class="operator" id="CookbookVersionConstraints">Operator</th>
            <th class="version" id="CookbookVersionConstraints">Version</th>
            <th class="last" id="CookbookVersionConstraints">&nbsp;</th>
          </tr>
          <tr id="cbVerAddRow">
              <td>
                <select size="1" name="cookbook_selector"
                        id="cookbook_name_0000"
                        onchange="jQuerySuggest('0000')"
                        onfocus="clearCookbookError()">
                  <option value=""></option>
                  <% @cookbooks.each do |book| %>
                  <option value="<%= book %>"><%= book %></option>
                  <% end %>
                </select>
              </td>
              <td>
                <select size="1" name="cookbook_operator_selector"
                        id="cookbook_operator_selector">
                  <% constraint_operators.each do |op| %>
                  <option value="<%= op %>"><%= op %></option>
                  <% end %>
                </select>
              </td>
              <td>
                <input id="cookbook_version_0000"
                       class="text" name="cookbook_version_selector"
                       onfocus="clearVersionBox(this, '0000')"
                       onblur="validateVersionBoxValue(this, '0000')"
                       value="0.0.0">
              </td>
              <td>
                <a href="javascript:void(0)"
                   onclick="addTableRow0000()">Add</a>
              </td>
            </tr>
        </tbody>
      </table>
    </div>

    <div class="group form attrEditor">
      <label class="label">Environment Default and Override Attributes</label>
      <%= render 'layouts/jsonedit', :json => { :defaults => @environment.default_attributes, :overrides => @environment.override_attributes }.to_json %>
      <span class="description">
        A JSON hash for attributes of this environment. These attributes will be applied according to the attribute precedence rules.
      </span>
    </div>

    <div class="group">
      <div class="actions-bar">
        <%= submit_tag submit_name, :id => submit_id, :class => 'button' %>
      </div>
    </div>
  <% end =%>
</div>

<script type='text/javascript'>
  function cookbook_versions() {
    return <%= cookbook_version_constraints.to_json %>;
  }
</script>
<script type='text/javascript' charset="utf-8" src="/javascripts/cookbook_constraint_ctrl.js"></script>

chef-server-webui/app/views/environments/_navigation.html.haml
.secondary-navigation
  %ul
    %li{ :class => "first #{active == 'index' ? "active" : ''}"}= link_to('List', environments_path)
    %li{ :class => (active == 'create' ? "active" : '')}= link_to('Create', new_environment_path)
    - if active != 'create' && active != 'index'
      %li{ :class => (active == 'show' ? "active" : '')}= link_to('Show', environment_path(@environment.name))
      %li{ :class => (active == 'edit' ? "active" : '')}= link_to('Edit', edit_environment_path(@environment.name))
      %li= link_to('Delete', environment_path(@environment.name), :method => "delete", :confirm => "Really delete Environment #{@environment.name}? There is no undo.")
  .clear

chef-server-webui/app/views/environments/_version_selector.html.erb
<div class="cookbook_version_constraint_control_container">
  <span class="label">
    <label for="cookbook_version[<%= cookbook_version_index -%>]">cookbook version constraint:</label>
  </span>
  <span>
    <%= text_field_tag "cookbook_version[#{cookbook_version_index}]", "#{cookbook_name} #{constraint}" %>
  </span>
</div>

chef-server-webui/app/views/environments/edit.html.erb
<div id="block-tables" class="block">
  <div class="content">
    <h2 class="title">Environment <%= params[:id] %></h2>
    <div class="inner">
      <%= render "environments/navigation", :environment => @environment, :active => 'edit' %>
    </div>
    <%= render 'environments/form',  :environment => @environment,
                                      :route => :environments,
                                      :method => :put,
                                      :form_url => environment_path(@environment.name),
                                      :form_id => 'edit_environment',
                                      :form_for => 'edit',
                                      :submit_name => "Update Environment",
                                      :submit_id => "edit_environment_button",
                                      :new_object => true %>
  </div>
</div>

chef-server-webui/app/views/environments/index.html.haml
.block#block-tables
  .content
    %h2.title Environments
    .inner
      = render('navigation', :active => 'index')
    .content
      .inner
        %table.table
          %tr
            %th.first{:colspan => 2} Name
            %th &nbsp;
            %th.last &nbsp;
          - even = false;
          - @environment_list.sort_by {|key,value| key.downcase}.each do |env|
            %tr{ :class => even ? "even" : "odd" }
              %td{:colspan => 2}= link_to(env[0], environment_path(env[0]))
              %td
                - if session[:environment] != env[0]
                  = link_to('Select', environment_select_path(env[0]))
                - else
                  Select
                |
                = link_to('Edit', edit_environment_path(env[0]))
                |
                = link_to('Delete', environment_path(env[0]), :method => "delete", :confirm => "Really delete Environment #{env[0]}?  there is no undo.")
              - even = (not even)

chef-server-webui/app/views/environments/new.html.erb
<div id="block-tables" class="block">
  <div class="content">
    <h2 class="title">Environment <%= params[:id] %></h2>
    <div class="inner">
      <%= render "environments/navigation", :environment => @environment, :active => 'create'%>
    </div>
    <%= render 'environments/form',  :environment => @environment,
                                      :route => :environments,
                                      :method => :post,
                                      :form_url => environments_path,
                                      :form_id => 'create_environment',
                                      :form_for => 'create',
                                      :submit_name => "Create Environment",
                                      :submit_id => "create_environment_button",
                                      :new_object => true %>
  </div>
</div>

chef-server-webui/app/views/environments/show.html.haml
.block#block-tables
  .content
    %h2.title= "Environment #{h @environment.name}"
    .inner
      = render("navigation", :active => "show")
      .content
        .inner
          .left
            %h3 Name
            = @environment.name
          .left
            %h3 Description
            = @environment.description
          .left
            %h3 Cookbook Version Constraints
            %table.table
              %tr
                %th.first Name
                %th.last Version Constraints
              - if @environment.cookbook_versions.empty?
                %tr
                  %td{:colspan => 2} This environment does not include any cookbook version constraints.
              - else
                - @environment.cookbook_versions.keys.sort.each do |name|
                  - versions = @environment.cookbook_versions[name]
                  %tr
                    %td= name
                    %td= versions

          .left
            %h3 Default Attributes
            = build_tree('defattrs', @environment.default_attributes)

          .left
            %h3 Override Attributes
            = build_tree('overattrs', @environment.override_attributes)