chef-server-webui/config/routes.rb
#
# Author:: Adam Jacob (<adam@opscode.com>)
# Author:: Daniel DeLeo (<dan@opscode.com>)
# Copyright:: Copyright (c) 2008-2010 Opscode, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

ChefServerWebui::Application.routes.draw do
  resources :nodes, :id => /[^\/]+/
  match "/nodes/_environments/:environment_id", :to => "nodes#index", :as => :nodes_by_environment

  resources :clients, :id => /[^\/]+/
  resources :roles

  resources :environments do
    match "/recipes", :only => :get, :to => "environments#list_recipes"
    match "/cookbooks", :to => "environments#list_cookbooks", :as => :cookbooks, :only => :get
    match "/nodes", :to => "environments#list_nodes", :as => :nodes, :only => :get
    match "/select", :to => "environments#select_environment", :as => :select, :only => :get
  end

  # match '/environments/create' :to => "environments#create", :as => :environments_create

  match "/status", :to => "status#index", :as => :status, :only => :get

  resources :searches, :path => "search", :controller => "search"
  match "/search/:search_id/entries", :only => 'get', :to => "search_entries", :action => "index"
  match "/search/:search_id/entries", :only => 'post', :to => "search_entries", :action => "create"
  match "/search/:search_id/entries/:id", :only => 'get', :to => "search_entries", :action => "show"
  match "/search/:search_id/entries/:id", :only => 'put', :to => "search_entries", :action => "create"
  match "/search/:search_id/entries/:id", :only => 'post', :to => "search_entries", :action => "update"
  match "/search/:search_id/entries/:id", :only => 'delete', :to => "search_entries", :action => "destroy"

  match "/cookbooks/_attribute_files", :to => "cookbooks#attribute_files"
  match "/cookbooks/_recipe_files", :to => "cookbooks#recipe_files"
  match "/cookbooks/_definition_files", :to => "cookbooks#definition_files"
  match "/cookbooks/_library_files", :to => "cookbooks#library_files"
  match "/cookbooks/_environments/:environment_id", :to => "cookbooks#index", :as => :cookbooks_by_environment

  match "/cookbooks/:cookbook_id", :cookbook_id => /[\w\.]+/, :only => :get, :to => "cookbooks#cb_versions"
  match "/cookbooks/:cookbook_id/:cb_version", :cb_version => /[\w\.]+/, :only => :get, :to => "cookbooks#show", :as => :show_specific_version_cookbook
  resources :cookbooks

  resources :clients

  match "/databags/:databag_id/databag_items", :only => :get, :to => "databags#show", :id=>":databag_id"

  resources :databags do
    resources :databag_items
  end

  match '/openid/consumer', :to => 'openid_consumer#index', :as => :openid_consumer
  match '/openid/consumer/start', :to => 'openid_consumer#start', :as => :openid_consumer_start
  match '/openid/consumer/login', :to => 'openid_consumer#login', :as => :openid_consumer_login
  match '/openid/consumer/complete', :to => 'openid_consumer#complete', :as => :openid_consumer_complete
  match '/openid/consumer/logout', :to => 'openid_consumer#logout', :as => :openid_consumer_logout

  match '/login', :to => 'users#login', :as => :users_login
  match '/logout', :to => 'users#logout', :as => :users_logout

  match '/users', :to => 'users#index', :as => :users
  match '/users/create', :to => 'users#create', :as => :users_create
  match '/users/start', :to => 'users#start', :as => :users_start

  match '/users/login', :to => 'users#login', :as => :users_login
  match '/users/login_exec', :to => 'users#login_exec', :as => :users_login_exec
  match '/users/complete', :to => 'users#complete', :as => :users_complete
  match '/users/logout', :to => 'users#logout', :as => :users_logout
  match '/users/new', :to => 'users#new', :as => :users_new
  match '/users/:user_id/edit', :to => 'users#edit', :as => :users_edit
  match '/users/:user_id', :to => 'users#show', :as => :users_show
  match '/users/:user_id/delete', :only => :delete, :to => 'users#destroy', :as => :users_delete
  match '/users/:user_id/update', :only => :put, :to => 'users#update', :as => :users_update

  match '/', :to => 'nodes#index', :as => :top
end

chef-server-webui/app/controllers/users_controller.rb
#
# Author:: Nuo Yan (<nuo@opscode.com>)
# Copyright:: Copyright (c) 2008 Opscode, Inc.
# License:: Apache License, Version 2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

require 'chef/webui_user'
require 'uri'

class UsersController < ApplicationController

  respond_to :html
  before_filter :login_required, :except => [:login, :login_exec, :complete]
  before_filter :require_admin, :except => [:login, :login_exec, :complete, :show, :edit, :logout, :destroy]

  # List users, only if the user is admin.
  def index
    begin
      @users = Chef::WebUIUser.list
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      set_user_and_redirect
    end
  end

  # Edit user. Admin can edit everyone, non-admin user can only edit itself.
  def edit
    begin
      @user = Chef::WebUIUser.load(params[:user_id])
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      set_user_and_redirect
    end
  end

  # Show the details of a user. If the user is not admin, only able to show itself; otherwise able to show everyone
  def show
    begin
      @user = Chef::WebUIUser.load(params[:user_id])
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      set_user_and_redirect
    end
  end

  # PUT to /users/:user_id/update
  def update
    begin
      @user = Chef::WebUIUser.load(params[:user_id])

      if session[:level] == :admin and !is_last_admin?
        @user.admin = params[:admin] =~ /1/ ? true : false
      end

      if params[:user_id] == session[:user] && params[:admin] == 'false'
        session[:level] = :user
      end

      if not params[:new_password].nil? and not params[:new_password].length == 0
        @user.set_password(params[:new_password], params[:confirm_new_password])
      end

      if params[:openid].length == 0 or params[:openid].nil?
        @user.set_openid(nil)
      else
        @user.set_openid(URI.parse(params[:openid]).normalize.to_s)
      end
      @user.save
      flash[:notice] = "Updated user #{@user.name}."
      render :show
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      @u = Chef::WebUIUser.load(params[:user_id])
      flash[:error] = "Could not update user #{@user.name}."
      render :edit
    end
  end

  def new
    begin
      @user = Chef::WebUIUser.new
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      set_user_and_redirect
    end
  end

  def create
    begin
      @user = Chef::WebUIUser.new
      @user.name = params[:name]
      @user.set_password(params[:password], params[:password2])
      @user.admin = true if params[:admin]
      (params[:openid].length == 0 || params[:openid].nil?) ? @user.set_openid(nil) : @user.set_openid(URI.parse(params[:openid]).normalize.to_s)
      @user.create
      redirect_to users_url, :notice => "Created User #{params[:name]}"
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      flash[:error] = "Could not create user"
      session[:level] != :admin ? set_user_and_redirect : (render :new)
    end
  end

  def login
    @user = Chef::WebUIUser.new
    session[:user] ? (redirect_to nodes_url, :flash => { :warning => "You've already logged in with user #{session[:user]}" } ) : (render :layout => 'login')
  end

  def login_exec
    begin
      @user = Chef::WebUIUser.load(params[:name])
      raise(Unauthorized, "Wrong username or password.") unless @user.verify_password(params[:password])
      complete
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      @user = Chef::WebUIUser.new
      flash[:error] = "Could not complete logging in."
      @environments = []
      render :login
    end
  end

  def complete
    session[:user] = params[:name]
    session[:level] = (@user.admin == true ? :admin : :user)
    (@user.name == Chef::Config[:web_ui_admin_user_name] && @user.verify_password(Chef::Config[:web_ui_admin_default_password])) ? redirect_to(users_edit_url(@user.name), :flash => { :warning => "Please change the default password" }) : redirect_back_or_default(nodes_url)
  end

  def logout
    cleanup_session
    redirect_to top_url
  end

  def destroy
    begin
      raise Forbidden, "A non-admin user can only delete itself" if (params[:user_id] != session[:user] && session[:level] != :admin)
      raise Forbidden, "The last admin user cannot be deleted" if (is_admin? && is_last_admin? && session[:user] == params[:user_id])
      @user = Chef::WebUIUser.load(params[:user_id])
      @user.destroy
      logout if params[:user_id] == session[:user]
      redirect_to users_url, :notice => "User #{params[:user_id]} deleted successfully."
    rescue => e
      Chef::Log.error("#{e}\n#{e.backtrace.join("\n")}")
      session[:level] != :admin ? set_user_and_redirect : redirect_to_list_users({ :error => $! })
    end
  end

  private

    def set_user_and_redirect
      begin
        @user = Chef::WebUIUser.load(session[:user]) rescue (raise NotFound, "Cannot find User #{session[:user]}, maybe it got deleted by an Administrator.")
      rescue
        logout_and_redirect_to_login
      else
        redirect_to users_show_url(session[:user]), :error => $!
      end
    end

    def redirect_to_list_users(message)
      flash = message
      @users = Chef::WebUIUser.list
      render :index
    end

end

chef-server-webui/app/views/users/_form.html.haml
.content
  .inner
    = form_tag form_url, :method => :post, :id => form_id, :class => 'form' do
      -if form_for == "login"
        %div.group
          .text_field= text_field_tag "name", params.has_key?(:name) ? h(params[:name]) : @user.name, :id => "user_name", :label => "Username: "
        %br/

        %div.group
          .text_field= password_field_tag "password", "", :id => "password", :label => "Password: ", :class => "password_field"
        %br/
        =link_to("Or, log in with OpenID if you have one associated with an existing user account.", openid_consumer_path)
        %br/

      - if form_for == "edit"
        %div.group.form
          %label.label New Password
          = password_field "new_password", "", :id => "user_new_password", :class => "password_field"
          %span.description New password for the User. Keep blank if you do not want to change password.

        %div.group.form
          %label.label Confirm New Password
          = password_field "confirm_new_password", "", :id => "user_confirm_new_password", :class =>"password_field"
          %span.description Confirm new password for the User. Keep blank if you do not want to change password.

        - if is_admin? && !is_last_admin?
          %div.group.form
            %label.label Admin
            %input{ :type => "hidden", :name => "admin", :value => 0 }
            %input{ :type => "checkbox", :name => "admin", :value => 1, :checked => @user.admin }
            %span.description Whether or not the User is an admin.

        %div.group.form
          %label.label OpenID Association
          = text_field_tag "openid", @user.openid, :id => "openid", :class => "text_field"
          %span.description Associate an OpenID with the user account, leave blank if you do not want to associate one.

      %div.group
        .actions-bar
          .actions= submit_tag submit_name, :id => submit_id, :class => 'button'

chef-server-webui/app/views/users/_navigation.html.haml
.secondary-navigation
  %ul
    - if is_admin?
      %li{ :class => "first #{active == 'index' ? "active" : ''}"}= link_to('List', users_path)
    - if is_admin?
      %li{ :class => (active == 'create' ? "active" : '')}= link_to('Create', users_new_path)
    - if active != 'create' && active != 'index'
      %li{ :class => (active == 'show' ? "active" : '')}= link_to('Show', users_show_path)
      - if @user.admin || @user.name == params[:user_id]
        %li{ :class => (active == 'edit' ? "active" : '')}= link_to('Edit', users_edit_path(params[:user_id]))
        %li= link_to('Delete', users_delete_path(params[:user_id]), :method => "delete", :confirm => "Really delete user #{params[:user_id]}? There is no undo.")
  .clear

chef-server-webui/app/views/users/_sidebar_block_notice.html.haml
%h4 Where do I get a Login?
%p Any existing Admin level user can create new users.
%p To create the first user, please login with the default admin credential, which by default is:
%p username: admin, password: p@ssw0rd1 (May be different if you've set it in Chef::Config)
%b Please change the default password immediately after logging in!
%p Once you have an User, you can associate an OpenID with the User and login using the OpenID as the User.
%p Administrators can associate OpenID to any User.

chef-server-webui/app/views/users/edit.html.haml
.block#block-tables
  .content
    %h2.title= "Edit user: #{h @user.name}"
    .inner
      = render('navigation', :active => 'edit')
  = render('form', :header => "Edit User #{@user.name}", :form_id => 'edit_user', :submit_name => "Save User", :submit_id => "edit_user_button", :form_for => 'edit', :form_url => users_update_path(@user.name) )

chef-server-webui/app/views/users/index.html.haml
.block#block-tables
  .content
    %h2.title Users
    .inner
      = render('navigation', :active => 'index')
    .content
      .inner
        %table.table
          %tr
            %th.first{:colspan => 2} Username
            %th &nbsp;
            %th.last &nbsp;
          - even = false
          - @users.sort_by {|key,value| key.downcase}.each do |user, user_url|
            %tr{:class => even ? "even": "odd" }
              %td{:colspan => 2}= link_to user, users_show_path(user)
              %td
                = link_to('Edit', users_edit_path(user))
                |
                = link_to('Delete', users_delete_path(user), :method => "delete", :confirm => "Really delete User #{user}?  There is no undo.")

chef-server-webui/app/views/users/login.html.haml
- content_for :sidebar_block_notice do
  %h4 Where do I get a Login?
  %p Any existing Admin level user can create new users.
  %p To create the first user, please login with the default admin credential, which by default is:
  %p username: admin, password: p@ssw0rd1 (May be different if you've set it in Chef::Config)
  %b Please change the default password immediately after logging in!
  %p Once you have an User, you can associate an OpenID with the User and login using the OpenID as the User.
  %p Administrators can associate OpenID to any User.

.block#block-forms
  .content
    %h2.title Login
    .inner
  = render('form', :header => "Login", :form_id => 'login', :submit_name => "login", :submit_id => "login_button", :form_for => 'login', :form_url => users_login_exec_url)

chef-server-webui/app/views/users/new.html.haml
.block#block-forms
  .content
    %h2.title Create New User
    .inner
      = render('navigation', :active => 'create')
    .content
      .inner
        %form.form{ :method => "get", "accept-charset" => "UTF-8", :action => users_create_path }
          %table.table
            %tr
              %td= "Username"
              %td= text_field_tag :name
            %tr
              %td= "Password"
              %td= password_field_tag :password
            %tr
              %td= "Confirm Password"
              %td= password_field_tag :password2
            %tr
              %td= "Admin"
              %td= check_box_tag "admin", "1"
            %tr
              %td= "OpenID (optional)"
              %td= text_field_tag :openid

          .group.navform
            .button= submit_tag "Create"

chef-server-webui/app/views/users/show.html.haml
.block#block-tables
  .content
    %h2.title= "User: #{h @user.name}"
    .inner
      = render("navigation", :active => "show")
      .content
        .inner
          .left
            %h3 Admin
            = @user.admin
          .left
            %h3 OpenID
            = @user.openid || "No OpenID associated to this user account."

chef-server-webui/app/views/users/start.html.haml
<%= @form_text %>
<script type="text/javascript">
document.getElementById('users_form').submit();
</script>